const mongoose = require("mongoose");
require("dotenv").config();
const Event = require("./models/Event");

// connect to our database
mongoose.connect(process.env.MONGO_URL);

async function seed() {
  await Event.create([
    {
      OrganizerName: "Alexandra Martinez",
      Name: "Tech Women Empowerment Forum",
      Location: "Innovation Hub",
      EventTitle: "Empowering Women in Tech",
      DateTime: "2023-07-08T11:00:00",
      Duration: "3.5 hours",
      Description:
        "A forum dedicated to empowering and supporting women in the tech industry. Join us for insightful discussions, networking opportunities, and career guidance.",
      FilterTags: ["women"],
      PictureOptionUpload: "event_images/tech_women_empowerment_forum.jpg",
      SocialMediaLink: "https://linkedin.com/in/alexandramartinez",
      TicketPrice: 20.0,
      QuantityTickets: 200,
    },
    {
      OrganizerName: "David Rodriguez",
      Name: "LGBTQ+ Pride Parade",
      Location: "City Streets",
      EventTitle: "Celebrating Diversity with Pride",
      DateTime: "2023-06-25T15:00:00",
      Duration: "5 hours",
      Description:
        "Join us for a vibrant Pride Parade celebrating love, acceptance, and the LGBTQ+ community. Dance, march, and show your pride!",
      FilterTags: ["LGBTQ+"],
      PictureOptionUpload: "event_images/pride_parade.jpg",
      SocialMediaLink: "https://twitter.com/davidrodriguez",
      TicketPrice: 0.0,
      QuantityTickets: 500,
    },
    {
      OrganizerName: "Emily Thompson",
      Name: "Cultural Harmony Festival",
      Location: "City Park",
      EventTitle: "Unity in Diversity",
      DateTime: "2023-09-01T14:00:00",
      Duration: "4 hours",
      Description:
        "An inclusive festival celebrating cultural diversity. Enjoy music, dance, and food from around the world.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/cultural_harmony_festival.jpg",
      SocialMediaLink: "https://www.instagram.com/emilythompson",
      TicketPrice: 15.0,
      QuantityTickets: 300,
    },
    {
      OrganizerName: "Michael Chen",
      Name: "STEM for All Conference",
      Location: "Science Center",
      EventTitle: "Advancing STEM Education",
      DateTime: "2023-08-15T09:30:00",
      Duration: "6 hours",
      Description:
        "A conference focused on promoting STEM education for all. Engage with experts, attend workshops, and explore exciting developments in science and technology.",
      FilterTags: ["women", "LGBTQ+"],
      PictureOptionUpload: "event_images/stem_for_all_conference.jpg",
      SocialMediaLink: "https://www.linkedin.com/in/michaelchen",
      TicketPrice: 25.0,
      QuantityTickets: 250,
    },
    {
      OrganizerName: "Sophia Davis",
      Name: "AccessArt Exhibition",
      Location: "Modern Art Gallery",
      EventTitle: "Art Access for Everyone",
      DateTime: "2023-07-20T18:30:00",
      Duration: "3 hours",
      Description:
        "An exhibition showcasing artworks created by artists with various abilities. Explore the power of art as a universal language.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/accessart_exhibition.jpg",
      SocialMediaLink: "https://www.twitter.com/sophiadavis",
      TicketPrice: 10.0,
      QuantityTickets: 150,
    },
    {
      OrganizerName: "Nina Patel",
      Name: "Tech Inclusion Workshop",
      Location: "Tech Hub Labs",
      EventTitle: "Building an Inclusive Tech Community",
      DateTime: "2023-06-30T14:00:00",
      Duration: "2.5 hours",
      Description:
        "A workshop on promoting diversity and inclusion in the tech industry. Learn about best practices and strategies for building inclusive teams.",
      FilterTags: ["women", "LGBTQ+"],
      PictureOptionUpload: "event_images/tech_inclusion_workshop.jpg",
      SocialMediaLink: "https://www.linkedin.com/in/ninapatel",
      TicketPrice: 15.0,
      QuantityTickets: 200,
    },
    {
      OrganizerName: "Brian Thompson",
      Name: "Unity in Sports Tournament",
      Location: "City Sports Complex",
      EventTitle: "Sports for All Abilities",
      DateTime: "2023-08-05T10:00:00",
      Duration: "7 hours",
      Description:
        "A sports tournament emphasizing inclusivity. Join us for a day of friendly competition, camaraderie, and celebration.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/unity_in_sports_tournament.jpg",
      SocialMediaLink: "https://www.facebook.com/brianthompson",
      TicketPrice: 12.0,
      QuantityTickets: 180,
    },
    {
      OrganizerName: "Isabel Rodriguez",
      Name: "Women in Science Symposium",
      Location: "Science Institute",
      EventTitle: "Celebrating Women's Contributions to Science",
      DateTime: "2023-09-10T13:30:00",
      Duration: "4 hours",
      Description:
        "A symposium highlighting the achievements of women in science. Engage with inspiring speakers and participate in discussions on gender equality in STEM.",
      FilterTags: ["women"],
      PictureOptionUpload: "event_images/women_in_science_symposium.jpg",
      SocialMediaLink: "https://twitter.com/isabelrodriguez",
      TicketPrice: 18.0,
      QuantityTickets: 220,
    },
    {
      OrganizerName: "Chris Wilson",
      Name: "Inclusive Design Workshop",
      Location: "Design Studio",
      EventTitle: "Designing for Diversity",
      DateTime: "2023-07-12T15:30:00",
      Duration: "3 hours",
      Description:
        "A workshop on inclusive design principles. Explore how design can address diverse user needs and create accessible products and spaces.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/inclusive_design_workshop.jpg",
      SocialMediaLink: "https://www.linkedin.com/in/chriswilson",
      TicketPrice: 20.0,
      QuantityTickets: 120,
    },
    {
      OrganizerName: "Maria Sanchez",
      Name: "Culinary Diversity Festival",
      Location: "City Square",
      EventTitle: "Taste the World: Culinary Delights",
      DateTime: "2023-08-28T17:00:00",
      Duration: "5 hours",
      Description:
        "A festival celebrating diverse cuisines from around the world. Experience the richness of global culinary traditions.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/culinary_diversity_festival.jpg",
      SocialMediaLink: "https://www.instagram.com/mariasanchez",
      TicketPrice: 15.0,
      QuantityTickets: 250,
    },
    {
      OrganizerName: "Jason Patel",
      Name: "Tech for Good Hackathon",
      Location: "Innovation Hub",
      EventTitle: "Hacking for Positive Impact",
      DateTime: "2023-07-25T09:00:00",
      Duration: "24 hours",
      Description:
        "A hackathon focused on developing innovative solutions to address social and environmental challenges. Join us in using technology for positive change.",
      FilterTags: ["LGBTQ+"],
      PictureOptionUpload: "event_images/tech_for_good_hackathon.jpg",
      SocialMediaLink: "https://twitter.com/jasonpatel",
      TicketPrice: 0.0,
      QuantityTickets: 300,
    },
    {
      OrganizerName: "Ava Brown",
      Name: "Empower Youth Workshop",
      Location: "Community Center",
      EventTitle: "Inspiring the Next Generation",
      DateTime: "2023-09-15T14:30:00",
      Duration: "3 hours",
      Description:
        "A workshop focused on empowering and inspiring youth. Engage in mentorship, skill-building activities, and discussions on personal development.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/empower_youth_workshop.jpg",
      SocialMediaLink: "https://www.facebook.com/avabrown",
      TicketPrice: 10.0,
      QuantityTickets: 150,
    },
    {
      OrganizerName: "Daniel Garcia",
      Name: "Music Without Borders Concert",
      Location: "City Amphitheater",
      EventTitle: "Celebrating Cultural Harmony through Music",
      DateTime: "2023-08-18T19:00:00",
      Duration: "4 hours",
      Description:
        "A concert featuring musicians from diverse backgrounds. Immerse yourself in the beauty of music without borders.",
      FilterTags: ["LGBTQ+"],
      PictureOptionUpload: "event_images/music_without_borders_concert.jpg",
      SocialMediaLink: "https://www.instagram.com/danielgarcia",
      TicketPrice: 25.0,
      QuantityTickets: 180,
    },
    {
      OrganizerName: "Sophie Miller",
      Name: "Art Beyond Limits Exhibition",
      Location: "Modern Art Gallery",
      EventTitle: "Exploring Limitless Creativity",
      DateTime: "2023-07-05T17:30:00",
      Duration: "3.5 hours",
      Description:
        "An exhibition showcasing artworks created by artists with disabilities. Experience the boundless creativity of the human spirit.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/art_beyond_limits_exhibition.jpg",
      SocialMediaLink: "https://www.twitter.com/sophiemiller",
      TicketPrice: 12.0,
      QuantityTickets: 120,
    },
    {
      OrganizerName: "Aaron Davis",
      Name: "STEM Education Fair",
      Location: "City Science Center",
      EventTitle: "Inspiring Future Scientists",
      DateTime: "2023-09-05T10:00:00",
      Duration: "5 hours",
      Description:
        "A fair showcasing interactive exhibits and activities to inspire children and young adults to pursue STEM education and careers.",
      FilterTags: ["women", "LGBTQ+"],
      PictureOptionUpload: "event_images/stem_education_fair.jpg",
      SocialMediaLink: "https://www.linkedin.com/in/aarondavis",
      TicketPrice: 10.0,
      QuantityTickets: 250,
    },
    {
      OrganizerName: "Olivia White",
      Name: "Dance Fusion Showcase",
      Location: "City Dance Studio",
      EventTitle: "Celebrating Diversity through Dance",
      DateTime: "2023-08-02T18:30:00",
      Duration: "2 hours",
      Description:
        "A dance showcase featuring diverse dance styles and cultural expressions. Celebrate the beauty of movement and expression.",
      FilterTags: ["LGBTQ+"],
      PictureOptionUpload: "event_images/dance_fusion_showcase.jpg",
      SocialMediaLink: "https://www.instagram.com/oliviawhite",
      TicketPrice: 18.0,
      QuantityTickets: 150,
    },
    {
      OrganizerName: "Ethan Wilson",
      Name: "Diverse Voices Poetry Night",
      Location: "City Arts Center",
      EventTitle: "Voices of the Unheard",
      DateTime: "2023-07-22T20:00:00",
      Duration: "2.5 hours",
      Description:
        "An evening of poetry and spoken word performances by artists from diverse backgrounds. Listen to the voices of the unheard.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/diverse_voices_poetry_night.jpg",
      SocialMediaLink: "https://twitter.com/ethanwilson",
      TicketPrice: 15.0,
      QuantityTickets: 120,
    },
    {
      OrganizerName: "Aria Johnson",
      Name: "Inclusive Tech Expo",
      Location: "Tech Expo Center",
      EventTitle: "Showcasing Inclusive Technologies",
      DateTime: "2023-08-10T12:00:00",
      Duration: "6 hours",
      Description:
        "An expo featuring innovative technologies designed with inclusivity in mind. Explore the latest advancements in accessible tech.",
      FilterTags: ["disabled"],
      PictureOptionUpload: "event_images/inclusive_tech_expo.jpg",
      SocialMediaLink: "https://www.linkedin.com/in/ariajohnson",
      TicketPrice: 20.0,
      QuantityTickets: 180,
    },
  ]);

  console.log("Movie created");
  mongoose.disconnect();
}

seed();
